version: "3.8"

services:
  database:
    container_name: database
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - 3030:3030

  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - 3000:3000
